services:
  - type: web
    name: cryptotop
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: cryptotop-db
          property: connectionString

databases:
  - name: cryptotop-db
    plan: free
    databaseName: cryptotop
    user: cryptotop_user

